-- MySQL Script generated by MySQL Workbench
-- Wed Feb 19 08:50:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestorSalones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestorSalones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestorSalones` DEFAULT CHARACTER SET utf8 ;
USE `gestorSalones` ;

-- -----------------------------------------------------
-- Table `gestorSalones`.`coordinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorSalones`.`coordinador` (
  `cooId` INT NOT NULL AUTO_INCREMENT,
  `cooNombre` VARCHAR(45) NOT NULL,
  `cooCorreo` VARCHAR(45) NOT NULL,
  `cooUsuario` VARCHAR(45) NOT NULL,
  `cooPasswd` VARCHAR(45) NOT NULL,
  `cooPrograma` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `cooUsuario_UNIQUE` (`cooUsuario` ASC),
  PRIMARY KEY (`cooId`),
  UNIQUE INDEX `cooId_UNIQUE` (`cooId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorSalones`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorSalones`.`materia` (
  `matId` INT NOT NULL AUTO_INCREMENT,
  `matCodigo` VARCHAR(45) NOT NULL,
  `matNombre` VARCHAR(45) NOT NULL,
  `matEstudiantes` INT NOT NULL,
  `matIntensidadHoraria` INT NOT NULL,
  `matPrioridadHorario` VARCHAR(45) NOT NULL,
  `matRestriccionSalon` VARCHAR(45) NOT NULL,
  `matNombreProfesor` VARCHAR(45) NOT NULL,
  `matContactoProfesor` VARCHAR(45) NULL,
  `coordinador_cooId` INT NOT NULL,
  PRIMARY KEY (`matId`, `coordinador_cooId`),
  UNIQUE INDEX `matId_UNIQUE` (`matId` ASC),
  UNIQUE INDEX `matCodigo_UNIQUE` (`matCodigo` ASC),
  INDEX `fk_materia_coordinador1_idx` (`coordinador_cooId` ASC),
  CONSTRAINT `fk_materia_coordinador1`
    FOREIGN KEY (`coordinador_cooId`)
    REFERENCES `gestorSalones`.`coordinador` (`cooId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorSalones`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorSalones`.`profesor` (
  `proId` INT NOT NULL AUTO_INCREMENT,
  `proNombre` VARCHAR(45) NOT NULL,
  `proCorreo` VARCHAR(45) NOT NULL,
  `proPasswd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`proId`),
  UNIQUE INDEX `proId_UNIQUE` (`proId` ASC),
  UNIQUE INDEX `proCorreo_UNIQUE` (`proCorreo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorSalones`.`salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorSalones`.`salon` (
  `salId` INT NOT NULL AUTO_INCREMENT,
  `salNombre` VARCHAR(45) NOT NULL,
  `salHabilitado` INT NOT NULL,
  `salCapRecomendada` INT NOT NULL,
  `salUbicacion` VARCHAR(45) NULL,
  `salCapMaxima` INT NULL,
  `salVideobeam` VARCHAR(45) NULL,
  `salTv` VARCHAR(45) NULL,
  `salPuntoRed` VARCHAR(45) NULL,
  `salPuntoEnergia` VARCHAR(45) NULL,
  `salWifi` VARCHAR(45) NULL,
  `salVentilador` VARCHAR(45) NULL,
  `salCortinas` VARCHAR(45) NULL,
  `salNumTableros` VARCHAR(45) NULL,
  `salEncargado` VARCHAR(45) NULL,
  PRIMARY KEY (`salId`),
  UNIQUE INDEX `salId_UNIQUE` (`salId` ASC),
  UNIQUE INDEX `salNombre_UNIQUE` (`salNombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorSalones`.`materia_has_salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorSalones`.`materia_has_salon` (
  `materia_matId` INT NOT NULL,
  `salon_salId` INT NOT NULL,
  `dia` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`materia_matId`, `salon_salId`),
  INDEX `fk_materia_has_salon_salon1_idx` (`salon_salId` ASC),
  INDEX `fk_materia_has_salon_materia1_idx` (`materia_matId` ASC),
  CONSTRAINT `fk_materia_has_salon_materia1`
    FOREIGN KEY (`materia_matId`)
    REFERENCES `gestorSalones`.`materia` (`matId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_has_salon_salon1`
    FOREIGN KEY (`salon_salId`)
    REFERENCES `gestorSalones`.`salon` (`salId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
