-- MySQL Script generated by MySQL Workbench
-- Tue Feb 11 10:44:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestorSalones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestorSalones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestorSalones` DEFAULT CHARACTER SET utf8 ;
USE `gestorSalones` ;

-- -----------------------------------------------------
-- Table `gestorSalones`.`coordinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorSalones`.`coordinador` (
  `cooId` INT NOT NULL AUTO_INCREMENT,
  `cooNombre` VARCHAR(45) NOT NULL,
  `cooCorreo` VARCHAR(45) NOT NULL,
  `cooUsuario` VARCHAR(45) NOT NULL,
  `cooPasswd` VARCHAR(45) NOT NULL,
  `cooPrograma` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `cooUsuario_UNIQUE` (`cooUsuario` ASC),
  PRIMARY KEY (`cooId`),
  UNIQUE INDEX `cooId_UNIQUE` (`cooId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorSalones`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorSalones`.`materia` (
  `matId` VARCHAR(45) NOT NULL,
  `matNombre` VARCHAR(45) NOT NULL,
  `matEstudiantes` INT NOT NULL,
  `matIntensidadHoraria` INT NOT NULL,
  `matPrioridadHorario` VARCHAR(45) NOT NULL,
  `matRestriccionSalon` VARCHAR(45) NOT NULL,
  `matDiasAsignados` VARCHAR(45) NULL,
  `matHorasAsignadas` VARCHAR(45) NULL,
  `matNombreProfesor` VARCHAR(45) NOT NULL,
  `matContactoProfesor` VARCHAR(45) NULL,
  `coordinador_cooId` INT NOT NULL,
  PRIMARY KEY (`matId`),
  UNIQUE INDEX `matId_UNIQUE` (`matId` ASC),
  INDEX `fk_materia_coordinador_idx` (`coordinador_cooId` ASC),
  CONSTRAINT `fk_materia_coordinador`
    FOREIGN KEY (`coordinador_cooId`)
    REFERENCES `gestorSalones`.`coordinador` (`cooId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorSalones`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorSalones`.`profesor` (
  `proId` INT NOT NULL,
  `proNombre` VARCHAR(45) NOT NULL,
  `proCorreo` VARCHAR(45) NOT NULL,
  `proPasswd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`proId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
